/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
 // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  sidebar: [
    'intro',
    {
      type: 'category',
      label: 'AWS',
      items: ['Data Ingestion/Cloud Logs/aws', 'Data Ingestion/Cloud Logs/cloudtrail', 'Data Ingestion/Cloud Logs/alb', 'Data Ingestion/Cloud Logs/s3-access', 'Data Ingestion/Cloud Logs/vpc-flow', 'Data Ingestion/Cloud Logs/waf'],
    },
  ],

};

module.exports = sidebars;
